server:
  port: 8080

spring:
  application:
    name: whoistobuy-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/witb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql:
